name: pet_system
description: Sistema de gerenciamento para pets

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP requests
  http: ^1.1.0
  
  # State management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^12.1.3
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # UI components
  flutter_svg: ^2.0.9
  
  # Icons
  cupertino_icons: ^1.0.2
  
  # Image picker for web
  image_picker: ^1.0.4
  
  # Responsive design
  responsive_framework: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Comentado temporariamente até criar os diretórios
  # assets:
  #   - assets/images/
  #   - assets/icons/

web:
  meta_tags:
    viewport: width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no