server:
  port: 8080

spring:
  application:
    name: pet-conect-api
  
  datasource:
    url: jdbc:postgresql://localhost:5432/petconect
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  sql:
    init:
      mode: never

  main:
    allow-circular-references: true

jwt:
  secret: HjYRFRA33EGMq7LNea0+IjDlUENWNrlJMaKz0VBgCTnDZ3r5jiTxxltGxKeThTmh
  expiration: 86400000 # 24 horas em millisegundos

cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

logging:
  level:
    com.petconect: DEBUG
    org.springframework.security: DEBUG 